name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Install dependencies
        working-directory: nodeapp
        run: npm i
      - name: Test and coverage
        working-directory: nodeapp
        run: npm test -- --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ecdf1a51-172b-4f59-b9dd-94e40ef32417
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
